<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <title>DKPiles</title>
    <link rel="icon" type="image/png" href="./assets/media/logo-olas.png"/>
    <link rel="stylesheet" href="./assets/css/main.css">
    <link rel="stylesheet" href="./assets/css/eventos.css">

    <script src="./scripts/js/main.js"></script>
</head>
<body>
    <div class="container">
        <!-- HEADER -->
        <header class="header"><?php require "./assets/components/header.html" ?></header>


        <!-- MAIN -->
        <main>
            <h1>Términos de uso y política de privacidad</h1>
            <h2 dir="ltr" style="line-height:2.172342857142857;margin-top:18pt;margin-bottom:4pt;"><span style="font-size:17.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Aviso legal y t&eacute;rminos de uso</span></h2>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En este espacio, el USUARIO, podr&aacute; encontrar toda la informaci&oacute;n relativa a los t&eacute;rminos y condiciones legales que definen las relaciones entre los usuarios y nosotros como responsables de esta web. Como usuario, es importante que conozcas estos t&eacute;rminos antes de continuar tu navegaci&oacute;n. Club N&aacute;utico DKPiles, como responsable de esta web, asume el compromiso de procesar la informaci&oacute;n de nuestros usuarios y clientes con plenas garant&iacute;as y cumplir con los requisitos nacionales y europeos que regulan la recopilaci&oacute;n y uso de los datos personales de nuestros usuarios. Esta web, por tanto, cumple rigurosamente con el RGPD (REGLAMENTO (UE) 2016/679 de protecci&oacute;n de datos) y la LSSI-CE la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la informaci&oacute;n y de comercio electr&oacute;nico.</span></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CONDICIONES GENERALES DE USO</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Las presentes Condiciones Generales regulan el uso (incluyendo el mero acceso) de las p&aacute;ginas de la web, integrantes del sitio web de dkpiles.es incluidos los contenidos y servicios puestos a disposici&oacute;n en ellas. Toda persona que acceda a la web, dkpiles.es (&ldquo;Usuario&rdquo;) acepta someterse a las Condiciones Generales vigentes en cada momento del portal dkpiles.es.</span></p>
            <p><br></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DATOS PERSONALES QUE RECABAMOS Y C&Oacute;MO LO HACEMOS</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:10pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Leer&nbsp;</span><a href="https://policies.google.com/privacy?hl=es" style="text-decoration:none;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#039be5;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Pol&iacute;tica de Privacidad</span></a></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">COMPROMISOS Y OBLIGACIONES DE LOS USUARIOS</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El Usuario queda informado, y acepta, que el acceso a la presente web no supone, en modo alguno, el inicio de una relaci&oacute;n comercial con dkpiles.es. De esta forma, el usuario se compromete a utilizar el sitio Web, sus servicios y contenidos sin contravenir la legislaci&oacute;n vigente, la buena fe y el orden p&uacute;blico.</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Queda prohibido el uso de la web, con fines il&iacute;citos o lesivos, o que, de cualquier forma, puedan causar perjuicio o impedir el normal funcionamiento del sitio web. Respecto de los contenidos de esta web, se proh&iacute;be:&nbsp;</span></p>
            <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Su reproducci&oacute;n, distribuci&oacute;n o modificaci&oacute;n, total o parcial, a menos que se cuente con la autorizaci&oacute;n de sus leg&iacute;timos titulares</span></p>
                </li>
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cualquier vulneraci&oacute;n de los derechos del prestador o de los leg&iacute;timos titulares</span></p>
                </li>
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:0pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Su utilizaci&oacute;n para fines comerciales o publicitarios.</span></p>
                </li>
            </ul>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En la utilizaci&oacute;n de la web, dkpiles.es, el Usuario se compromete a no llevar a cabo ninguna conducta que pudiera da&ntilde;ar la imagen, los intereses y los derechos de dkpiles.es o de terceros o que pudiera da&ntilde;ar, inutilizar o sobrecargar el portal dkpiles.es o que impidiera, de cualquier forma, la normal utilizaci&oacute;n de la web. No obstante, el Usuario debe ser consciente de que las medidas de seguridad de los sistemas inform&aacute;ticos en Internet no son enteramente fiables y que, por tanto dkpiles.es no puede garantizar la inexistencia de virus u otros elementos que puedan producir alteraciones en los sistemas inform&aacute;ticos (software y hardware) del Usuario o en sus documentos electr&oacute;nicos y ficheros contenidos en los mismos.</span></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">MEDIDAS DE SEGURIDAD</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Los datos personales comunicados por el usuario a dkpiles.es pueden ser almacenados en bases de datos automatizadas o no, cuya titularidad corresponde en exclusiva a dkpiles.es, asumiendo &eacute;sta todas las medidas de &iacute;ndole t&eacute;cnica, organizativa y de seguridad que garantizan la confidencialidad, integridad y calidad de la informaci&oacute;n contenida en las mismas de acuerdo con lo establecido en la normativa vigente en protecci&oacute;n de datos.</span></p>
            <p><br></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La comunicaci&oacute;n entre los usuarios y dkpiles.es utiliza un canal seguro, y los datos transmitidos son cifrados gracias a protocolos a https, por tanto, garantizamos las mejores condiciones de seguridad para que la confidencialidad de los usuarios est&eacute; garantizada.</span></p>
            <p><br></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">RECLAMACIONES</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">dkpiles.es informa que existen hojas de reclamaci&oacute;n a disposici&oacute;n de usuarios y clientes. El Usuario podr&aacute; realizar reclamaciones solicitando su hoja de reclamaci&oacute;n o remitiendo un correo electr&oacute;nico a&nbsp;</span><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#039be5;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DKPiles@gmail.com</span><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;indicando su nombre y apellidos, el servicio y/o producto adquirido y exponiendo los motivos de su reclamaci&oacute;n.</span></p>
            <p><br></p>
            <p><br></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El usuario/comprador podr&aacute; notificarnos la reclamaci&oacute;n, bien a trav&eacute;s de correo electr&oacute;nico a:&nbsp;</span><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#039be5;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DKPiles@gmail.com</span><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, si lo desea adjuntando el siguiente formulario de reclamaci&oacute;n:&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El servicio/producto:&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Adquirido el d&iacute;a:&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Nombre del usuario:&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Domicilio del usuario:&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Firma del usuario (solo si se presenta en papel):&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Fecha:&nbsp;</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Motivo de la reclamaci&oacute;n:</span></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">PLATAFORMA DE RESOLUCI&Oacute;N DE CONFLICTOS</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Por si puede ser de tu inter&eacute;s, para someter tus reclamaciones puedes utilizar tambi&eacute;n la plataforma de resoluci&oacute;n de litigios que facilita la Comisi&oacute;n Europea y que se encuentra disponible en el siguiente enlace:&nbsp;</span><a href="http://ec.europa.eu/consumers/odr/" style="text-decoration:none;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#039be5;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">http://ec.europa.eu/consumers/odr/</span></a></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En virtud de lo dispuesto en los art&iacute;culos 8 y 32.1, p&aacute;rrafo segundo, de la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducci&oacute;n, la distribuci&oacute;n y la comunicaci&oacute;n p&uacute;blica, incluida su modalidad de puesta a disposici&oacute;n, de la totalidad o parte de los contenidos de esta p&aacute;gina web, con fines comerciales, en cualquier soporte y por cualquier medio t&eacute;cnico, sin la autorizaci&oacute;n de dkpiles.es. El usuario se compromete a respetar los derechos de Propiedad Intelectual e Industrial titularidad de dkpiles.es.</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El usuario conoce y acepta que la totalidad del sitio web, conteniendo sin car&aacute;cter exhaustivo el texto, software, contenidos (incluyendo estructura, selecci&oacute;n, ordenaci&oacute;n y presentaci&oacute;n de los mismos) podcast, fotograf&iacute;as, material audiovisual y gr&aacute;ficos, est&aacute; protegida por marcas, derechos de autor y otros derechos leg&iacute;timos, de acuerdo con los tratados internacionales en los que Espa&ntilde;a es parte y otros derechos de propiedad y leyes de Espa&ntilde;a. En el caso de que un usuario o un tercero consideren que se ha producido una violaci&oacute;n de sus leg&iacute;timos derechos de propiedad intelectual por la introducci&oacute;n de un determinado contenido en la web, deber&aacute; notificar dicha circunstancia a dkpiles.es indicando:</span></p>
            <p dir="ltr" style="line-height:1.68;margin-left: 36pt;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Datos personales del interesado titular de los derechos presuntamente infringidos, o indicar la representaci&oacute;n con la que act&uacute;a en caso de que la reclamaci&oacute;n la presente un tercero distinto del interesado.</span></p>
            <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                <li dir="ltr" style="list-style-type:none;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Se&ntilde;alar los contenidos protegidos por los derechos de propiedad intelectual y su ubicaci&oacute;n en la web, la acreditaci&oacute;n de los derechos de propiedad intelectual se&ntilde;alados y declaraci&oacute;n expresa en la que el interesado se responsabiliza de la veracidad de las informaciones facilitadas en la notificaci&oacute;n</span></p>
                </li>
                <li dir="ltr" style="list-style-type:none;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;"><br></li>
            </ul>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ENLACES EXTERNOS</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Las p&aacute;ginas de la web dkpiles.es podr&iacute;an proporcionar enlaces a otros sitios web propios y contenidos que son propiedad de terceros. El &uacute;nico objeto de los enlaces es proporcionar al Usuario la posibilidad de acceder a dichos enlaces. dkpiles.es no se responsabiliza en ning&uacute;n caso de los resultados que puedan derivarse al Usuario por acceso a dichos enlaces.</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Asimismo, el usuario encontrar&aacute; dentro de este sitio, p&aacute;ginas, promociones, programas de afiliados que acceden a los h&aacute;bitos de navegaci&oacute;n de los usuarios para establecer perfiles. Esta informaci&oacute;n siempre es an&oacute;nima y no se identifica al usuario.</span></p>
            <p><br></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La Informaci&oacute;n que se proporcione en estos Sitios patrocinados o enlaces de afiliados est&aacute; sujeta a las pol&iacute;ticas de privacidad que se utilicen en dichos Sitios y no estar&aacute; sujeta a esta pol&iacute;tica de privacidad. Por lo que recomendamos ampliamente a los Usuarios a revisar detalladamente las pol&iacute;ticas de privacidad de los enlaces de afiliado.</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El Usuario que se proponga establecer cualquier dispositivo t&eacute;cnico de enlace desde su sitio web al portal dkpiles.es deber&aacute; obtener la autorizaci&oacute;n previa y escrita de dkpiles.es El establecimiento del enlace no implica en ning&uacute;n caso la existencia de relaciones entre dkpiles.es y el propietario del sitio en el que se establezca el enlace, ni la aceptaci&oacute;n o aprobaci&oacute;n por parte de dkpiles.es de sus contenidos o servicios</span></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">POL&Iacute;TICA DE COMENTARIOS</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En nuestra web se permiten realizar comentarios para enriquecer los contenidos y realizar consultas. No se admitir&aacute;n comentarios que no est&eacute;n relacionados con la tem&aacute;tica de esta web, que incluyan difamaciones, agravios, insultos, ataques personales o faltas de respeto en general hacia el autor o hacia otros miembros. Tambi&eacute;n ser&aacute;n suprimidos los comentarios que contengan informaci&oacute;n que sea obviamente enga&ntilde;osa o falsa, as&iacute; como los comentarios que contengan informaci&oacute;n personal, como, por ejemplo, domicilios privado o tel&eacute;fonos y que vulneren nuestra pol&iacute;tica de protecci&oacute;n de datos.</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Se desestimar&aacute;, igualmente, aquellos comentarios creados s&oacute;lo con fines promocionales de una web, persona o colectivo y todo lo que pueda ser considerado spam en general.</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">No se permiten comentarios an&oacute;nimos, as&iacute; como aquellos realizados por una misma persona con distintos apodos. No se considerar&aacute;n tampoco aquellos comentarios que intenten forzar un debate o una toma de postura por otro usuario.</span></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">EXCLUSI&Oacute;N DE GARANT&Iacute;AS Y RESPONSABILIDAD</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El Prestador no otorga ninguna garant&iacute;a ni se hace responsable, en ning&uacute;n caso, de los da&ntilde;os y perjuicios de cualquier naturaleza que pudieran traer causa de:</span></p>
            <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La falta de disponibilidad, mantenimiento y efectivo funcionamiento de la web, o de sus servicios y contenidos</span></p>
                </li>
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La existencia de virus, programas maliciosos o lesivos en los contenidos</span></p>
                </li>
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El uso il&iacute;cito, negligente, fraudulento o contrario a este Aviso Legal</span></p>
                </li>
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La falta de licitud, calidad, fiabilidad, utilidad y disponibilidad de los servicios prestados por terceros y puestos a disposici&oacute;n de los usuarios en el sitio web</span></p>
                </li>
                <li dir="ltr" style="list-style-type:disc;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
                    <p dir="ltr" style="line-height:1.68;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El prestador no se hace responsable bajo ning&uacute;n concepto de los da&ntilde;os que pudieran dimanar del uso ilegal o indebido de la presente p&aacute;gina web</span></p>
                </li>
                <li dir="ltr" style="list-style-type:none;font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;"><br></li>
            </ul>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">LEY APLICABLE Y JURISDICCI&Oacute;N</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Con car&aacute;cter general las relaciones entre dkpiles.es con los Usuarios de sus servicios telem&aacute;ticos, presentes en esta web se encuentran sometidas a la legislaci&oacute;n y jurisdicci&oacute;n espa&ntilde;olas y a los tribunales.</span></p>
            <p><br></p>
            <h3 dir="ltr" style="line-height:1.76;margin-top:14pt;margin-bottom:4pt;"><span style="font-size:13.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CONTACTO</span></h3>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En caso de que cualquier Usuario tuviese alguna duda acerca de estas Condiciones legales o cualquier comentario sobre el portal dkpiles.es, por favor dir&iacute;jase a&nbsp;</span><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#039be5;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DKPiles@gmail.com</span></p>
            <p dir="ltr" style="line-height:1.68;margin-top:11pt;margin-bottom:11pt;"><span style="font-size:11.5pt;font-family:Roboto,sans-serif;color:#666666;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">De parte del equipo que formamos Club N&aacute;utico DKPiles te agradecemos el tiempo dedicado en leer este Aviso Legal</span></p>       
        </main>

        <!-- ASIDE -->
        <aside><?php require "./assets/components/aside.html" ?></aside>
       

        <!-- FOOTER -->
        <footer><?php require "./assets/components/footer.html" ?></footer>
    </div>

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <scrip src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></scrip>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <script type="text/javascript">
        $(() => { loadComponents('Eventos') });
    </script>
</body>
</html>